### ISSUE TITLE
Why stderr instead of stdout?

### ISSUE THREAD

**Issue by germelcar** [doches/progressbar#21]
Thanks you guys for your progressbar, I have used it for a school's project where I have to implement a genetic algorithm for solving QAP (Quadratic Assigment Problem), but I have found in the code that you use "stderr" instead of "stdout," why is it?

The progressbar works (I have not tried userbar) because by default stderr = stdout. I mean, if I run my application and redirect the error output to some log file (as many Li**g**nux (GNU/Linux) applications do - usually /var/log/ directory), the progressbar will not be displayed in the terminal. I think that it will be better to change "stderr" by "stdout."

Thanks.

**Comment by kirbyfan64** [comment]
FWIW, Curl writes the progress bar to stderr.

**Comment by doches** [comment]
@germelcar Imagine that I have a long-running program that reads input from stdin and writes transformed output to stdout. It's long-running, so I want to have a progress bar to tell me if I have time to go make a coffee before it finishes -- but I can't have that progress bar write to stdout, or it'll get interleaved with my output.

Basically, if I use pipes in the proper Unix-y way, writing to stdout would be a disaster! What if I did:

```bash
./long_running_program < input.txt > output.txt
```

I'd end up with the output of `long_running_program` all mixed up with my progress bar together in `output.txt`.
