### ISSUE TITLE
Suggestion: show how it looks like.

### ISSUE THREAD

**Issue by g-p-g** [doches/progressbar#3]
I just uploaded this thing at https://asciinema.org/a/8vvbdlvp7pj3557o6q5mv7wsk which you could embed here using `[![asciicast](https://asciinema.org/a/8vvbdlvp7pj3557o6q5mv7wsk.png)](https://asciinema.org/a/8vvbdlvp7pj3557o6q5mv7wsk)`.

**Comment by doches** [comment]
Yep, a demo/screenshot would go a long way. I don't want to introduce a dependency on a random third-party service (however useful asciinema looks!), but I *have* added a screenshot of the demo program to the README. Thanks for the suggestion!
